// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnz-Ri0Pmqij0oVvqGXqtTC5jVs5VK8oM',
    appId: '1:1032245913405:web:bdd55a93a23e02d0bbc754',
    messagingSenderId: '1032245913405',
    projectId: 'e-commerce-84a77',
    authDomain: 'e-commerce-84a77.firebaseapp.com',
    storageBucket: 'e-commerce-84a77.firebasestorage.app',
    measurementId: 'G-1CVE74VYX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Npj6XmwVynHEKZjIqFNTaPTxIhRERTg',
    appId: '1:1032245913405:android:e8a3beee101379abbbc754',
    messagingSenderId: '1032245913405',
    projectId: 'e-commerce-84a77',
    storageBucket: 'e-commerce-84a77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5crqLnGqU6l5CCnbV0RadyptK0S79DQM',
    appId: '1:1032245913405:ios:0726d7dd666546c4bbc754',
    messagingSenderId: '1032245913405',
    projectId: 'e-commerce-84a77',
    storageBucket: 'e-commerce-84a77.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
